import { configureOffline } from './support';
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
test('four guide sections and evidence work offline without a message', async ({page,context,browserName}) => {
  await configureOffline(context,browserName);
  const requests:string[]=[];
  page.on('request', r => {if(/^https?:/.test(r.url()))requests.push(r.url());});
  await page.goto(pathToFileURL(resolve('dist/index.html')).href);
  await expect(page.locator('#editor')).toHaveValue('');
  await expect(page.locator('.guide-card')).toHaveCount(4);
  await page.locator('.guide-teaser a').click();
  await page.locator('.overview-cards a[href="#guide-3"]').click();
  await page.getByRole('button',{name:'Run built-in checks'}).click();
  await expect(page.locator('#guide-test-results li')).toHaveCount(3);
  await expect(page.locator('#guide-test-results')).not.toContainText('Unexpected');
  await page.locator('.guide-nav a[href="#guide-4"]').click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download example evidence'}).click();
  const download=await downloadPromise;
  const report=JSON.parse(readFileSync((await download.path())!,'utf8'));
  expect(report.results.semantics[0].status).toBe('passed');
  const sample=await page.locator('#guide-sample').textContent();
  expect(report.input.sha256).toBe(createHash('sha256').update(sample!).digest('hex'));
  expect(report.results).toMatchObject({schema:true,context:'not checked'});
  await expect(page.locator('#editor')).toHaveValue('');
  await page.screenshot({path:'docs/guide-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('.guide-nav a[href="#guide-2"]').click();
  await page.locator('#guide-2').screenshot({path:'docs/guide-mobile.png'});
  expect(requests).toEqual([]);
});
