import { configureOffline } from './support';
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const url = pathToFileURL(resolve('dist/index.html')).href;
test('validator is home and guide navigation preserves work', async ({page,context,browserName}) => {
  await configureOffline(context,browserName);
  await page.goto(url);
  await expect(page.locator('#editor')).toBeVisible();
  await expect(page.locator('#guide-view')).toBeHidden();
  await page.screenshot({path:'docs/redesign-home.png',fullPage:true});
  await page.locator('#example').selectOption('Handshake');
  await page.locator('#validate').click();
  const original = await page.locator('#editor').inputValue();
  await page.locator('#nav-guide').click();
  await expect(page.locator('#validator-view')).toBeHidden();
  await expect(page.locator('#guide-overview')).toBeVisible();
  await page.locator('.overview-cards a[href="#guide-4"]').click();
  await expect(page.locator('#guide-4')).toBeVisible();
  await expect(page.locator('#guide-1')).toBeHidden();
  await page.locator('.back-link').click();
  await expect(page.locator('#editor')).toHaveValue(original);
  await expect(page.locator('#report h3')).toHaveText('Message matches the pinned schema');
  await page.goBack();
  await expect(page.locator('#guide-4')).toBeVisible();
  await page.reload();
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0);
  await expect(page.locator('#guide-4')).toBeVisible();
  await page.evaluate(readFileSync(resolve('node_modules/axe-core/axe.min.js'),'utf8'));
  const violations = await page.evaluate(async () => (await (window as any).axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations);
  expect(violations).toEqual([]);
  await page.screenshot({path:'docs/redesign-guide.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#nav-validator').click();
  await expect(page.locator('#editor')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:'docs/redesign-mobile.png',fullPage:true});
  await page.locator('#nav-guide').click();
  await page.locator('.overview-cards a[href="#guide-1"]').click();
  await page.locator('.brand').click();
  await expect(page.locator('#validator-view')).toBeVisible();
});
