import { configureOffline } from './support';
import {test,expect} from '@playwright/test';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
test('combined result and field panel remain clear and keyboard accessible',async({page,context,browserName},info)=>{
  await configureOffline(context,browserName);await page.goto(pathToFileURL(resolve('dist/index.html')).href);
  await page.locator('#editor').fill('{"message_type":"Handshake","message_id":"message-01","role":"RM"}');
  await page.locator('#validate').click();
  await expect(page.locator('#overall-summary')).toHaveText('Schema valid · 1 additional check failed');
  await expect(page.locator('#notice')).toContainText('1 additional check failed');
  await page.locator('.schema-tools > summary').click();
  const before=await page.locator('#editor').boundingBox();
  await page.locator('#open-reference').click();
  await expect(page.locator('#reference-panel')).toBeVisible();
  const after=await page.locator('#editor').boundingBox();
  expect(after?.y).toBe(before?.y);expect(after?.width).toBe(before?.width);
  await expect(page.locator('#close-reference')).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(page.locator('#reference-panel')).toBeHidden();
  await expect(page.locator('#open-reference')).toBeFocused();
  await page.locator('#example').selectOption('Handshake');await page.locator('#validate').click();
  await expect(page.locator('#overall-summary')).toHaveText('Schema valid · 1 additional check passed');
  await page.locator('#open-reference').click();
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:`docs/panel-${info.project.name}.png`,fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('#close-reference').click();
  await page.locator('#editor').fill('{"message_type":"PEBC.PowerConstraints"}');await page.locator('#validate').click();
  await expect(page.locator('#overall-summary')).toHaveText('This message needs attention');
});
